### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mikestreety** [jpmschuler/TYPO3-tvplus-contentslide#10]
Hey, 

Is there any chance we can get this commit into a proper release somewhere? (maybe v9.0.2) It's tripped me up a couple of times as you have to specify a `minimum-stability` to get it

Thanks

**Comment by jpmschuler** [comment]
you can actually specify the stability for a single package without changing minimum-stability, but yeah we can of course, all my tests are green

**Comment by mikestreety** [comment]
Oh interesting, how would I do that?

Thanks - appreciate it 👍

**Comment by jpmschuler** [comment]
in my `composer.json` I just got this to refer to a tagged version
```
		"jpmschuler/tvplus-contentslide": "*@alpha",
```
This allows 10.0.0-alpha.3, but as soon as 10.0.0 is released takes the stable, as it allows alpha, but doesn't enforce it.


or to refer to a branch things like
```
		"typo3/cms-css-styled-content": "dev-TYPO3_9.x",
```

**Comment by jpmschuler** [comment]
released https://packagist.org/packages/jpmschuler/tvplus-contentslide#v10.0.0
Added dependency to typo3db-legacy.

Still the refactoring to SitesAPI and Doctrine needs to be done, but as it seems to work nevertheless an initial release won't hurt.

**Comment by mikestreety** [comment]
Perfect - thank you!
