### ISSUE TITLE
[REGRESSION] wrong refactoring of getPageFlexValue do-loop causes no empty return if languageFallback array is empty

### ISSUE THREAD

**Issue by mikestreety** [jpmschuler/TYPO3-tvplus-contentslide#11]
Hey,

It seems [this commit](https://github.com/jpmschuler/TYPO3-tvplus-contentslide/commit/05d85fd5903ca89371c11f46cb1da0c531364b8e) introduced a regression (certainly for me). 

It seems to fail as [langaugeFallback](https://github.com/jpmschuler/TYPO3-tvplus-contentslide/blob/develop/Classes/SlideController.php#L184) is empty - which means the loop that follows fails and returns nothing.

I don't know enough about this bit of code to understand it and suggest a fix - replacing the method with the one on `v10.0.0-alpha2` fixes it for me

**Comment by jpmschuler** [comment]
My local tests are green, however I always just covered only a small portion of TemplaVoilà features. 
Could you elaborate how I could recreate this problem? E.g. supply the (excerpt of) DataStructure you are using and when and when not the slide works.

I understood the refactoring error and fixed the code and made it available as https://packagist.org/packages/jpmschuler/tvplus-contentslide#v10.0.1-alpha.1 
could you test if that resolves your issue.

I don't understand a good portion of that code either - although this is more about all those special possibilities concerning language configs, as I myself only use fallback.

**Comment by mikestreety** [comment]
Thanks for the quick response @jpmschuler  - i can confirm that `v10.0.1-alpha.2` works as expected

**Comment by jpmschuler** [comment]
Wonderful, marked v10.0.1 as stable then.
