### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by ksjogo** [jpmschuler/TYPO3-tvplus-contentslide#5]
Will/could/should this work with the upcoming v10 release?

**Comment by jpmschuler** [comment]
As soon as EXT:templavoilaplus has a stable v10 release, of course

**Comment by jpmschuler** [comment]
rels https://github.com/pluspol-interactive/templavoilaplus/issues/231
rels https://github.com/pluspol-interactive/templavoilaplus/milestone/18

**Comment by jpmschuler** [comment]
FWIW: https://packagist.org/packages/jpmschuler/tvplus-contentslide#v10.0.0-alpha.2 is there, although no concrete adaptions for v10 are implemented yet

**Comment by jpmschuler** [comment]
Released v11.0.2 which should have full EXT:templavoilaplus v8 compatibility:
- https://packagist.org/packages/jpmschuler/tvplus-contentslide#v11.0.2
- https://extensions.typo3.org/extension/tvplus_contentslide#v11.0.2

The previous v10.0.1 works on 10LTS with EXT:templavoilaplus v7 - e.g. using https://github.com/jpmschuler/templavoilaplus/tree/tv10-classic the hot fixed v7 based upon https://github.com/w010/templavoilaplus/) - although I never ran into problems, the language implementation was not adapted for full 10LTS compatibility
